### ISSUE TITLE
fail to get active sheet?

### ISSUE THREAD

**Issue by ericj** [dherbst/slack-invite-script#4]
1. After creating the form and paste the code to Script Editor 
2. Modify token and slack url; add trigger with "readRows from Form when submit"
3. Select the readRows function and click run, the script will fail with error message:

>    TypeError: Cannot call method "getDataRange" of null.

``` javascript
function readRows() {
  var sheet = SpreadsheetApp.getActiveSheet();
  var rows = sheet.getDataRange();
```

It seems like fail to get ActiveSheet?
Would you please help to show me if I missed any steps?

**Comment by dherbst** [comment]
Sorry didn't see this until now.  

Did you paste the code into the script editor for the spreadsheet the form populates?  Sounds like it cannot find the active sheet because you might be scripting the form.

**Comment by dherbst** [comment]
Closing with no response.
