### ISSUE TITLE
Slack URL and Channel IDs should be modifiable

### ISSUE THREAD

**Issue by drwl** [dherbst/slack-invite-script#5]
Great script; useful and works as intended.  
There are hard-coded slack subdomains and channel ids. These should be changed for each different instance. Otherwise you may see this error on your spreadsheet `{"ok":false,"error":"channel_not_found"}`.

**Comment by dherbst** [comment]
@drwl there are now functions up top to centralize where to change these things.

**Comment by dhalarewich** [comment]
Using latest code, I still had to edit the `payload.channels` line with the channel ID, otherwise I got the error mentioned above.
