### ISSUE TITLE
Channel.list

### ISSUE THREAD

**Issue by yooperdude** [dherbst/slack-invite-script#7]
Noticed one error, you need to specify the proper channel id. 

I found mine by going to : https://api.slack.com/methods/channels.list/test

Then once I had my ID I filled it into the payload.channels line.

Thanks much, script works great!

**Comment by dherbst** [comment]
The documentation https://api.slack.com/methods/chat.postMessage says

> Post to a public channel
> You can either pass the channel's name (#general) or encoded ID (C024BE91L), and the message will be posted to that channel. The channel's ID can be retrieved through the channels.list API method.

So it sort of depends on where you are trying to post the message.  I'll add it to the readme.
